# Update result statistics

on:
  push:
    paths:
      - .github/workflows/calc-result-stat.yaml
      - code/instances/results/calc-stat.R
      - code/instances/results/**.json
  schedule:
    - cron: '15 1,13 * * *'

name: Update result statistics

# Stop if a new push
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

jobs:
  calc-result-stat:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      RGL_USE_NULL: true
      DISPLAY: 99 # for rgl
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2

      - uses: r-lib/actions/setup-renv@v2
      
      - name: Update statistics for result files
        id: loop
        run: |
          for i in 1 2 3 4 5 6 7 8 9 10 11 12 13 
          do
            Rscript code/instances/results/calc-stat.R
            git config --local user.name "$GITHUB_ACTOR"
            git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
            git commit code/instances/results/. -m "update stat in result files" || echo "No changes to commit"
            git push origin || echo "No changes to commit"
          done
