# Update result statistics

on:
  push:
    paths:
      - .github/workflows/stat-prob.yaml
      - code/instances/stat-prob.R
      - code/instances/results/**.json
      - code/instances/problem-statistics.Rmd
      
  schedule:
    - cron: '15 5,17 * * *'

name: Update result statistics

# Stop if a new push
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

jobs:
  calc-result-stat:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      RGL_USE_NULL: true
      DISPLAY: 99 # for rgl
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2

      - uses: r-lib/actions/setup-renv@v2
      
      - name: Render (in case of error) 
        run: |
          Rscript -e 'rmarkdown::render(here::here("code/instances/problem-statistics.Rmd"), output_dir = here::here("docs"))'
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git commit docs/problem-statistics.html -m "update report" || echo "No changes to commit"
          git pull
          git push origin || echo "No changes to commit"
      
      - name: Update result statistics and render (in loop) 
        id: loop
        run: |
          for i in 1 2 3 4 5 6 
          do
            Rscript code/instances/stat-prob.R
            Rscript -e 'rmarkdown::render(here::here("code/instances/problem-statistics.Rmd"), output_dir = here::here("docs"))'
            git config --local user.name "$GITHUB_ACTOR"
            git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
            git commit docs/problem-statistics.html -m "update report" || echo "No changes to commit"
            git commit code/instances/. -m "update stat in result files" || echo "No changes to commit"
            git pull
            git push origin || echo "No changes to commit"
          done
          
